lettersToGovernment/config/routes.rb
Rails.application.routes.draw do
  resources :representatives
  resources :letters

  root 'letters#index'

end

lettersToGovernment/app/models/letter.rb
class Letter < ActiveRecord::Base
	has_many :subscriptions
	has_many :representatives, through: :subscriptions
	accepts_nested_attributes_for :representatives
end

lettersToGovernment/app/models/representative.rb
class Representative < ActiveRecord::Base
	has_many :subscriptions
	has_many :letters, through: :subscriptions

	def full_name
	   "#{self.first_name} #{self.last_name} (#{self.state}-#{self.party.chars.first})"
	end
end

lettersToGovernment/app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :letter
  belongs_to :representative
end

lettersToGovernment/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

lettersToGovernment/app/controllers/letters_controller.rb
class LettersController < ApplicationController
  before_action :set_letter, only: [:show, :edit, :update, :destroy]

  # GET /letters
  # GET /letters.json
  def index
    @letters = Letter.all
  end

  # GET /letters/1
  # GET /letters/1.json
  def show
  end

  # GET /letters/new
  def new
    @letter = Letter.new
  end

  # GET /letters/1/edit
  def edit
  end

  # POST /letters
  # POST /letters.json
  def create
    @letter = Letter.new(letter_params)

    respond_to do |format|
      if @letter.save
        format.html { redirect_to @letter, notice: 'Letter was successfully created.' }
        format.json { render :show, status: :created, location: @letter }
      else
        format.html { render :new }
        format.json { render json: @letter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /letters/1
  # PATCH/PUT /letters/1.json
  def update
    respond_to do |format|
      if @letter.update(letter_params)
        format.html { redirect_to @letter, notice: 'Letter was successfully updated.' }
        format.json { render :show, status: :ok, location: @letter }
      else
        format.html { render :edit }
        format.json { render json: @letter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /letters/1
  # DELETE /letters/1.json
  def destroy
    @letter.destroy
    respond_to do |format|
      format.html { redirect_to letters_url, notice: 'Letter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_letter
      @letter = Letter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def letter_params
      params.require(:letter).permit(:title, :subject, :body, :representative_ids => [])
    end
end

lettersToGovernment/app/controllers/representatives_controller.rb
class RepresentativesController < ApplicationController
  before_action :set_representative, only: [:show, :edit, :update, :destroy]

  # GET /representatives
  # GET /representatives.json
  def index
    @representatives = Representative.all
  end

  # GET /representatives/1
  # GET /representatives/1.json
  def show
  end

  # GET /representatives/new
  def new
    @representative = Representative.new
  end

  # GET /representatives/1/edit
  def edit
  end

  # POST /representatives
  # POST /representatives.json
  def create
    @representative = Representative.new(representative_params)

    respond_to do |format|
      if @representative.save
        format.html { redirect_to @representative, notice: 'Representative was successfully created.' }
        format.json { render :show, status: :created, location: @representative }
      else
        format.html { render :new }
        format.json { render json: @representative.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /representatives/1
  # PATCH/PUT /representatives/1.json
  def update
    respond_to do |format|
      if @representative.update(representative_params)
        format.html { redirect_to @representative, notice: 'Representative was successfully updated.' }
        format.json { render :show, status: :ok, location: @representative }
      else
        format.html { render :edit }
        format.json { render json: @representative.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /representatives/1
  # DELETE /representatives/1.json
  def destroy
    @representative.destroy
    respond_to do |format|
      format.html { redirect_to representatives_url, notice: 'Representative was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_representative
      @representative = Representative.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def representative_params
      params.require(:representative).permit(:first_name, :last_name, :state, :party, :office, :email)
    end
end

lettersToGovernment/app/helpers/application_helper.rb
module ApplicationHelper
end

lettersToGovernment/app/helpers/letters_helper.rb
module LettersHelper
end

lettersToGovernment/app/helpers/representatives_helper.rb
module RepresentativesHelper
end

lettersToGovernment/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LettersToGovernment</title>

  <%= stylesheet_link_tag "application", params[:controller], :media => "all" %>
  <%= javascript_include_tag "application", params[:controller] %>
  <meta name="viewport" content="width=device-width,initial-scale=1">

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

lettersToGovernment/app/views/letters/_form.html.erb
<div class="ui form">
	<%= simple_form_for(@letter, html: { multipart: true }) do |f| %>
		<%= f.error_notification %>

		<div class="form-inputs">
			<%= f.input :title, placeholder: 'Enter a title for this letter' %>
			<%= f.input :subject, placeholder: 'Enter an email subject' %>
			<%= f.input :body, placeholder: 'Write your letter...' %>
		</div>

		<div class="representatives">
			<%= f.association :representatives, collection: Representative.order(:first_name), label_method: :full_name, as: :check_boxes %>
		</div>
		
		
		
		<!--
		<select name="gender" class="ui dropdown" multiple="" id="select-representatives">
		  <option value="">Gender</option>
		  <option value="male">Male</option>
		  <option value="female">Female</option>
		</select>
		-->
		

		<div class="form-actions">
			<%= f.button :submit, class: 'ui blue button' %>
		</div>
	<% end %>
</div>

<script>
$('#select-representatives')
  .dropdown()
;

lettersToGovernment/app/views/letters/_menu.html.erb
<div class="ui text menu">
  <div class="item">
    <%= image_tag("flag.jpg") %>
  </div>
  <div class="item">
      <div class="ui icon input">
        <input type="text" placeholder="Search...">
        <i class="search link icon"></i>
      </div>
    </div>
	<div class="ui right icon item">
	  <%= link_to new_letter_path do %>
	    <i class="plus icon"></i>
	    <% end %>
	</div>
</div>

lettersToGovernment/app/views/letters/edit.html.erb
<h1>Editing Letter</h1>

<%= render 'form' %>

<%= link_to 'Show', @letter %> |
<%= link_to 'Back', letters_path %>

lettersToGovernment/app/views/letters/index.html.erb
<p id="notice"><%= notice %></p>

<div class="ui stackable grid" id="menu">
  <div class="two wide column tablet only computer only"></div>
  <div class="twelve wide column">
    <%= render 'menu' %>
  </div>
  <div class="two wide column tablet only computer only"></div>
</div>

<div class="ui stackable grid">
  <div class="two wide column tablet only computer only"></div>
  <div class="two wide column tablet only computer only" id="topic-list">
    <div class="ui vertical text menu">
      <div class="header item">Topics</div>
      <a class="item">
        Gun Violence
      </a>
      <a class="item">
        LGBT
      </a>
      <a class="item">
        Clean Energy
      </a>
      <a class="item">
        ISIS
      </a>
      <a class="item">
        Affordable Healthcare
      </a>
      <a class="item">
        Black Lives Matter
      </a>
      <a class="item">
        Student Debt
      </a>
      <div class="header item">Demonstrations</div>
      <a class="item">
        Berkeley, CA - July 7th
      </a>
      <a class="item">
        Cambridge, MA - July 15th
      </a>
    </div>
  </div>
  <div class="eight wide column" id = "letter-list">
    <table class="ui very basic collapsing celled table">
      <tbody>
        <% @letters.each do |letter| %>
            <tr>
              <td>
                <%= link_to letter do %>
                  <h4 class="ui header">
                    <div class="content">
                      <%= letter.title %>
                      <div class="sub header"><%= letter.subject %>
                    </div>
                    <div class="metadata">
                      <div class="buttons">
                        <button class="ui basic compact tiny button">
                          <i class="caret up icon"></i>
                          445
                        </button>
                        <button class="ui basic compact tiny button">
                          <i class="comments icon"></i>
                          23
                        </button>
                      </div>
                      <div class="tags">
                        <div class="ui label">
                          Gun Violence
                        </div>
                        <div class="ui label">
                          LGBT
                        </div>
                      </div>
                    </div>
                  </h4>
                <% end %>
              </td>
            </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="two wide column tablet only computer only">
    
  </div>
  <div class="two wide column tablet only computer only"></div>
</div>

lettersToGovernment/app/views/letters/new.html.erb
<div class="ui stackable grid">
  <div class="two wide column" id="back">
  	<%= link_to letters_path do %>
  		<i class="grey remove circular inverted icon"></i>
  	<% end %>
  </div>
  <div class="fourteen wide column" id="new-letter-form">
  	<div class="banner">
  		<h2>Write a new letter</h2>
  		<h3>Share your message and others may send it!</h3>
  	</div>
	<%= render 'form' %>
  </div>
</div>

lettersToGovernment/app/views/letters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @letter.title %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @letter.subject %>
</p>

<p>
  <strong>Body:</strong>
  <%= @letter.body %>
</p>

<%= link_to 'Edit', edit_letter_path(@letter) %> |
<%= link_to 'Back', letters_path %>

lettersToGovernment/app/views/representatives/_form.html.erb
<%= simple_form_for(@representative) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :state %>
    <%= f.input :party %>
    <%= f.input :office %>
    <%= f.input :email %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

lettersToGovernment/app/views/representatives/edit.html.erb
<h1>Editing Representative</h1>

<%= render 'form' %>

<%= link_to 'Show', @representative %> |
<%= link_to 'Back', representatives_path %>

lettersToGovernment/app/views/representatives/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Representatives</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>State</th>
      <th>Party</th>
      <th>Office</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @representatives.each do |representative| %>
      <tr>
        <td><%= representative.first_name %></td>
        <td><%= representative.last_name %></td>
        <td><%= representative.state %></td>
        <td><%= representative.party %></td>
        <td><%= representative.office %></td>
        <td><%= representative.email %></td>
        <td><%= link_to 'Show', representative %></td>
        <td><%= link_to 'Edit', edit_representative_path(representative) %></td>
        <td><%= link_to 'Destroy', representative, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Representative', new_representative_path %>

lettersToGovernment/app/views/representatives/new.html.erb
<h1>New Representative</h1>

<%= render 'form' %>

<%= link_to 'Back', representatives_path %>

lettersToGovernment/app/views/representatives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @representative.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @representative.last_name %>
</p>

<p>
  <strong>State:</strong>
  <%= @representative.state %>
</p>

<p>
  <strong>Party:</strong>
  <%= @representative.party %>
</p>

<p>
  <strong>Office:</strong>
  <%= @representative.office %>
</p>

<p>
  <strong>Email:</strong>
  <%= @representative.email %>
</p>

<%= link_to 'Edit', edit_representative_path(@representative) %> |
<%= link_to 'Back', representatives_path %>